language: python

services:
- docker

python:
- 3.5
- 3.6
- nightly

matrix:
  allow_failures:
  - python: nightly

install:
- pip install -U setuptools twine pip wheel
- pip install -r requirements-dev.txt
- pip install -U codecov

script:
- make cov
- python setup.py check -rms

after_success:
- codecov

sudo: false

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "Fn5RaVoU66e7609jKgJ8yMYyuxvPj+4lmg6cFh6hEv7dyp6UbHXxBUJKAeU3VS2I0L/IrC73Z/389J4B8aYcQAlk25WbN6TTtUa1d6Uu/4MZISdvNYtvFotqwcZR47ZcfA8n3IHjZezJbbAWy0flDLGR+3tDVSHP/E5r5GgB3Ok="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6
